issues:
  max-per-linter: 0
  max-same-issues: 0

run:
  deadline: 5m

linters:
  disable-all: true
  enable:
    # - deadcode
    - errcheck
    # - gofmt
    - goimports
    # - revive
    - gosimple
    - govet
    - ineffassign
    - nakedret
    - misspell
    - staticcheck
    # - structcheck
    - typecheck
    - unused
    - unconvert
    # - varcheck
    - vet
    - vetshadow

linters-settings:
  errcheck:
    ignore: github.com/spf13/pflag:MarkHidden
